const express = require('express')
const router = express.Router()
const attackController = require('../controllers/attack')
const { ensureAuth, ensureGuest } = require('../middleware/auth')

router.get('/', ensureAuth, attackController.getTime)
router.post('/create-attack-time', attackController.createAttackTime)
router.get('/attack-type', ensureAuth, attackController.getType)
router.post('/create-attack-type', attackController.createAttackType)
router.get('/pain-level', ensureAuth, attackController.getPainLevel)
router.post('/create-pain-level', attackController.createPainLevel)
router.get('/attack-location', ensureAuth, attackController.getLocation)
router.post('/create-attack-location', attackController.createAttackLocation)
router.get('/symptoms', ensureAuth, attackController.getSymptoms)
router.post('/create-symptoms', attackController.createSymptoms)
router.get('/triggers', ensureAuth, attackController.getTriggers)
router.post('/create-triggers', attackController.createTriggers)
router.get('/aura', ensureAuth, attackController.getAura)
router.post('/create-aura', attackController.createAura)
router.get('/medication', ensureAuth, attackController.getMedication)
router.post('/create-medication', attackController.createMedication)
router.get('/relief', ensureAuth, attackController.getRelief)
router.post('/create-relief', attackController.createRelief)
router.get('/activities', ensureAuth, attackController.getActivities)
router.post('/create-activities', attackController.createActivities)
router.get('/pain-location', ensureAuth, attackController.getPainLocation)
router.post('/create-pain-location', attackController.createPainLocation)
router.get('/summary', ensureAuth, attackController.getSummary)

module.exports = router